// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OngGio.Infrastructure.Persistence;

#nullable disable

namespace OngGio.Infrastructure.Migrations
{
    [DbContext(typeof(OngGioDbContext))]
    [Migration("20260614132405_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OngGio.Domain.Entities.BaoGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("MaBaoGia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("ThueSuat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TongTienSauThue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TongTienTruocThue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("bao_gia", (string)null);
                });

            modelBuilder.Entity("OngGio.Domain.Entities.ChiTietBaoGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaoGiaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<decimal>("DienTichSx1Cai")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DonGiaCuoi")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GiaNhanCong")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HInput")
                        .HasColumnType("numeric");

                    b.Property<int>("LoaiTonId")
                        .HasColumnType("integer");

                    b.Property<int>("NhomSanPhamId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PhuKien")
                        .HasColumnType("numeric");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ThanhTienTon")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TongDienTichLo")
                        .HasColumnType("numeric");

                    b.Property<string>("TrangThaiCongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TrongLuongKg")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.Property<decimal>("WInput")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BaoGiaId");

                    b.HasIndex("LoaiTonId");

                    b.HasIndex("NhomSanPhamId");

                    b.ToTable("chi_tiet_bao_gia", (string)null);
                });

            modelBuilder.Entity("OngGio.Domain.Entities.LoaiTon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BangBaremJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("bang_barem");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<decimal>("DoDay")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DonGiaM2")
                        .HasColumnType("numeric");

                    b.Property<decimal>("GiaSanCoDinh")
                        .HasColumnType("numeric");

                    b.Property<string>("ThuongHieu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("loai_ton", (string)null);
                });

            modelBuilder.Entity("OngGio.Domain.Entities.NhomSanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("HinhAnhMinhHoa")
                        .HasColumnType("text");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.ToTable("nhom_san_pham", (string)null);
                });

            modelBuilder.Entity("OngGio.Domain.Entities.ThamSoCoDinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<decimal>("GiaTriSo")
                        .HasColumnType("numeric");

                    b.Property<int>("NhomSanPhamId")
                        .HasColumnType("integer");

                    b.Property<string>("TenThamSo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("NhomSanPhamId");

                    b.ToTable("tham_so_co_dinh", (string)null);
                });

            modelBuilder.Entity("OngGio.Domain.Entities.ChiTietBaoGia", b =>
                {
                    b.HasOne("OngGio.Domain.Entities.BaoGia", "BaoGia")
                        .WithMany("ChiTietBaoGias")
                        .HasForeignKey("BaoGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OngGio.Domain.Entities.LoaiTon", "LoaiTon")
                        .WithMany("ChiTietBaoGias")
                        .HasForeignKey("LoaiTonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OngGio.Domain.Entities.NhomSanPham", "NhomSanPham")
                        .WithMany("ChiTietBaoGias")
                        .HasForeignKey("NhomSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaoGia");

                    b.Navigation("LoaiTon");

                    b.Navigation("NhomSanPham");
                });

            modelBuilder.Entity("OngGio.Domain.Entities.ThamSoCoDinh", b =>
                {
                    b.HasOne("OngGio.Domain.Entities.NhomSanPham", "NhomSanPham")
                        .WithMany("ThamSoCoDinhs")
                        .HasForeignKey("NhomSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhomSanPham");
                });

            modelBuilder.Entity("OngGio.Domain.Entities.BaoGia", b =>
                {
                    b.Navigation("ChiTietBaoGias");
                });

            modelBuilder.Entity("OngGio.Domain.Entities.LoaiTon", b =>
                {
                    b.Navigation("ChiTietBaoGias");
                });

            modelBuilder.Entity("OngGio.Domain.Entities.NhomSanPham", b =>
                {
                    b.Navigation("ChiTietBaoGias");

                    b.Navigation("ThamSoCoDinhs");
                });
#pragma warning restore 612, 618
        }
    }
}
